# Generated by Django 3.1.2 on 2020-11-01 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_auto_20201029_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outgoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
