# Generated by Django 3.1.2 on 2020-11-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_auto_20201101_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoing',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
