# Generated by Django 3.1.2 on 2020-11-10 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_outgoing_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneybox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('quota', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='YourGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
