# Generated by Django 3.1.2 on 2020-11-16 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0005_moneybox_yourgoal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Outgoing',
            new_name='Outgoings',
        ),
    ]
