# Generated by Django 3.1.2 on 2020-11-22 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0006_auto_20201116_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obligations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.TextField()),
                ('quantum', models.IntegerField()),
            ],
        ),
    ]
