# Generated by Django 3.1.2 on 2020-11-22 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0008_auto_20201122_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneybox',
            old_name='quota',
            new_name='wolumen',
        ),
        migrations.RenameField(
            model_name='obligations',
            old_name='category',
            new_name='kategoria',
        ),
        migrations.RenameField(
            model_name='outgoings',
            old_name='category',
            new_name='kategoria',
        ),
        migrations.RenameField(
            model_name='outgoings',
            old_name='amount',
            new_name='suma',
        ),
        migrations.RenameField(
            model_name='yourgoal',
            old_name='volume',
            new_name='cel',
        ),
    ]
