# Generated by Django 3.1.2 on 2020-11-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0009_auto_20201122_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourgoal',
            name='cel',
            field=models.IntegerField(max_length=10),
        ),
    ]
