# Generated by Django 3.1.2 on 2020-11-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0010_auto_20201125_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneybox',
            name='wolumen',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='obligations',
            name='kategoria',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='obligations',
            name='kwota',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='outgoings',
            name='kategoria',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='outgoings',
            name='suma',
            field=models.IntegerField(max_length=10),
        ),
    ]
