# Generated by Django 3.1.2 on 2020-11-25 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0013_yourgoal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneybox',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='obligations',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='outgoings',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='yourgoal',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
