# Generated by Django 3.1.2 on 2020-11-30 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0014_auto_20201125_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yourgoal',
            options={'get_latest_by': 'creation_date'},
        ),
    ]
