# Generated by Django 3.1.2 on 2020-11-30 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0015_auto_20201130_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yourgoal',
            options={'get_latest_by': 'date'},
        ),
    ]
