# Generated by Django 3.1.2 on 2020-11-30 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0016_auto_20201130_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yourgoal',
            options={},
        ),
    ]
