# Generated by Django 3.1.2 on 2020-12-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0019_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='outgoings',
            table='outgoings',
        ),
    ]
